from typing import List
from datetime import datetime
from sqlalchemy import Text, String, Boolean, BigInteger, TIMESTAMP, func, ForeignKey
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

class Base(DeclarativeBase):
    pass

# MODELS
class Post(Base):
    __tablename__ = 'posts'
    
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    title: Mapped[str] = mapped_column(String(100), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    published: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        server_default=func.now(), # generated by postgre
        nullable=False
    )
    owner_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    owner: Mapped["User"] = relationship("User", back_populates="posts")

    def __repr__(self):
        return f"<Post id={self.id}, title={self.title!r}>"

class User(Base):
    __tablename__='users'

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    email: Mapped[str] = mapped_column(String(50), nullable=False, unique=True)
    password: Mapped[str] = mapped_column(String(512), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        server_default=func.now(), # generated by postgre
        nullable=False
    )
    posts: Mapped[List["Post"]] = relationship("Post", back_populates="owner", cascade="all, delete")

    def __repr__(self):
        return f"<User id={self.id}, email={self.email!r}>"

class Vote(Base):
    __tablename__ ='votes'
    user_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("users.id", ondelete="CASCADE"), primary_key=True)
    post_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("posts.id", ondelete="CASCADE"), primary_key=True)

    def __repr__(self):
        return f"User Id={self.user_id}, Post Id={self.post_id}"